// Generated by https://quicktype.io

import { DesignacionCargo } from '../../designacion-cargo/models/designacion-cargo';

export class Curso {
  private _id: number;
  private _id_anio_escolar: string;
  private _cue_escuela: string;
  private _division: string;
  private _id_designacion_preseptor: null;
  private _id_designacion_tutor: string;
  private _anio_escolar: AnioEscolar;
  private _designacion_tutor: DesignacionCargo;
  private _designacion_preceptor: DesignacionCargo;
  private _estado: string;
  constructor(
    id: number,
    id_anio_escolar: string,
    cue_escuela: string,
    division: string,
    id_designacion_preseptor: null,
    id_designacion_tutor: string,
    anio_escolar: AnioEscolar,
    designacion_tutor: DesignacionCargo,
    designacion_preceptor: DesignacionCargo,
    estado:string
  ) {
    this.id = id;
    this.id_anio_escolar = id_anio_escolar;
    this.cue_escuela = cue_escuela;
    this.division = division;
    this.id_designacion_preseptor = id_designacion_preseptor;
    this.id_designacion_tutor = id_designacion_tutor;
    this.anio_escolar = anio_escolar;
    this.designacion_tutor = designacion_tutor;
    this.designacion_preceptor = designacion_preceptor;
    this._estado = estado;
  }

  static getInstance(obj: Object) {
    return new Curso(
      obj['id'],
      obj['id_anio_escolar'],
      obj['cue_escuela'],
      obj['division'],
      obj['id_designacion_preseptor'],
      obj['id_designacion_tutor'],
      obj['anio_escolar'],
      DesignacionCargo.getInstance(obj['designacion_tutor']),
      DesignacionCargo.getInstance(obj['designacion_preceptor']),
      obj['estado']
    );
  }



    /**
     * Getter estado
     * @return {string}
     */
	public get estado(): string {
		return this._estado;
	}

    /**
     * Setter estado
     * @param {string} value
     */
	public set estado(value: string) {
		this._estado = value;
	}


  get CursoDivision() {
    return `${this.anio_escolar.anio} ${this.division} - ${this.anio_escolar.plan_estudio.nombre_plan}`;
  }

  /**
   * Getter id
   * @return {number}
   */
  public get id(): number {
    return this._id;
  }

  /**
   * Getter id_anio_escolar
   * @return {string}
   */
  public get id_anio_escolar(): string {
    return this._id_anio_escolar;
  }

  /**
   * Getter cue_escuela
   * @return {string}
   */
  public get cue_escuela(): string {
    return this._cue_escuela;
  }

  /**
   * Getter division
   * @return {string}
   */
  public get division(): string {
    return this._division;
  }

  /**
   * Getter id_designacion_preseptor
   * @return {null}
   */
  public get id_designacion_preseptor(): null {
    return this._id_designacion_preseptor;
  }

  /**
   * Getter id_designacion_tutor
   * @return {string}
   */
  public get id_designacion_tutor(): string {
    return this._id_designacion_tutor;
  }

  /**
   * Getter anio_escolar
   * @return {AnioEscolar}
   */
  public get anio_escolar(): AnioEscolar {
    return this._anio_escolar;
  }

  /**
   * Getter designacion_tutor
   * @return {DesignacionCargo}
   */
  public get designacion_tutor(): DesignacionCargo {
    return this._designacion_tutor;
  }

  /**
   * Getter designacion_preceptor
   * @return {DesignacionCargo}
   */
  public get designacion_preceptor(): DesignacionCargo {
    return this._designacion_preceptor;
  }

  /**
   * Setter id
   * @param {number} value
   */
  public set id(value: number) {
    this._id = value;
  }

  /**
   * Setter id_anio_escolar
   * @param {string} value
   */
  public set id_anio_escolar(value: string) {
    this._id_anio_escolar = value;
  }

  /**
   * Setter cue_escuela
   * @param {string} value
   */
  public set cue_escuela(value: string) {
    this._cue_escuela = value;
  }

  /**
   * Setter division
   * @param {string} value
   */
  public set division(value: string) {
    this._division = value;
  }

  /**
   * Setter id_designacion_preseptor
   * @param {null} value
   */
  public set id_designacion_preseptor(value: null) {
    this._id_designacion_preseptor = value;
  }

  /**
   * Setter id_designacion_tutor
   * @param {string} value
   */
  public set id_designacion_tutor(value: string) {
    this._id_designacion_tutor = value;
  }

  /**
   * Setter anio_escolar
   * @param {AnioEscolar} value
   */
  public set anio_escolar(value: AnioEscolar) {
    this._anio_escolar = value;
  }

  /**
   * Setter designacion_tutor
   * @param {DesignacionCargo} value
   */
  public set designacion_tutor(value: DesignacionCargo) {
    this._designacion_tutor = value;
  }

  /**
   * Setter designacion_preceptor
   * @param {DesignacionCargo} value
   */
  public set designacion_preceptor(value: DesignacionCargo) {
    this._designacion_preceptor = value;
  }
}

export interface AnioEscolar {
  id: number;
  id_plan_estudio: string;
  anio: string;
  created_at: null;
  updated_at: null;
  deleted_at: null;
  plan_estudio: PlanEstudio;
}

export interface PlanEstudio {
  id: number;
  nombre_plan: string;
  ley_equivalencia: null;
  norma_dictamen: null;
  ley_aprobacion: null;
  borrado: string;
  created_at: null;
  updated_at: null;
  deleted_at: null;
}
