// Generated by https://quicktype.io

import { Agente } from '../../agentes/models/agente';
import { Cargo } from '../../cargos/models/cargo';

export class DesignacionCargo {
  private _id: number;
  private _fecha_alta: string;
  private _fecha_baja: string;
  private _id_cargo: number;
  private _id_agente: number;
  private _id_situacion_revista: number;
  private _estado: string;
  private _observaciones: string;
  private _cargo: Cargo;
  private _agente: Agente;
  private _situacion_revista: SituacionRevista;

  constructor(
    id: number,
    fecha_alta: string,
    fecha_baja: string,
    id_cargo: number,
    id_agente: number,
    id_situacion_revista: number,
    estado: string,
    observaciones: string,
    cargo: Cargo,
    agente: Agente,
    situacion_revista: SituacionRevista
  ) {
    this.id = id;
    this.fecha_alta = fecha_alta;
    this.fecha_baja = fecha_baja;
    this.id_cargo = id_cargo;
    this.id_agente = id_agente;
    this.id_situacion_revista = id_situacion_revista;
    this.estado = estado;
    this.observaciones = observaciones;
    this.cargo = cargo;
    this.agente = agente;
    this.situacion_revista = situacion_revista;
  }

  static getInstance(obj: Object) {

    return obj==null || obj=== undefined?null: new DesignacionCargo(
      obj['id'],
      obj['fecha_alta'],
      obj['fecha_baja'],
      obj['id_cargo'],
      obj['id_agente'],
      obj['id_situacion_revista'],
      obj['estado'],
      obj['observaciones'],
      Cargo.getInstance(obj['cargo']),
      Agente.getInstance(obj['agente']),
      obj['situacion_revista']
    );
  }

  /**
   * Getter id
   * @return {number}
   */
  public get id(): number {
    return this._id;
  }

  /**
   * Getter fecha_alta
   * @return {string}
   */
  public get fecha_alta(): string {
    return this._fecha_alta;
  }

  /**
   * Getter fecha_baja
   * @return {string}
   */
  public get fecha_baja(): string {
    return this._fecha_baja;
  }

  /**
   * Getter id_cargo
   * @return {number}
   */
  public get id_cargo(): number {
    return this._id_cargo;
  }

  /**
   * Getter id_agente
   * @return {number}
   */
  public get id_agente(): number {
    return this._id_agente;
  }

  /**
   * Getter id_situacion_revista
   * @return {number}
   */
  public get id_situacion_revista(): number {
    return this._id_situacion_revista;
  }

  /**
   * Getter estado
   * @return {string}
   */
  public get estado(): string {
    return this._estado;
  }

  /**
   * Getter observaciones
   * @return {string}
   */
  public get observaciones(): string {
    return this._observaciones;
  }

  /**
   * Getter cargo
   * @return {Cargo}
   */
  public get cargo(): Cargo {
    return this._cargo;
  }

  /**
   * Getter agente
   * @return {Agente}
   */
  public get agente(): Agente {
    return this._agente;
  }

  /**
   * Getter situacion_revista
   * @return {SituacionRevista}
   */
  public get situacion_revista(): SituacionRevista {
    return this._situacion_revista;
  }

  /**
   * Setter id
   * @param {number} value
   */
  public set id(value: number) {
    this._id = value;
  }

  /**
   * Setter fecha_alta
   * @param {string} value
   */
  public set fecha_alta(value: string) {
    this._fecha_alta = value;
  }

  /**
   * Setter fecha_baja
   * @param {string} value
   */
  public set fecha_baja(value: string) {
    this._fecha_baja = value;
  }

  /**
   * Setter id_cargo
   * @param {number} value
   */
  public set id_cargo(value: number) {
    this._id_cargo = value;
  }

  /**
   * Setter id_agente
   * @param {number} value
   */
  public set id_agente(value: number) {
    this._id_agente = value;
  }

  /**
   * Setter id_situacion_revista
   * @param {number} value
   */
  public set id_situacion_revista(value: number) {
    this._id_situacion_revista = value;
  }

  /**
   * Setter estado
   * @param {string} value
   */
  public set estado(value: string) {
    this._estado = value;
  }

  /**
   * Setter observaciones
   * @param {string} value
   */
  public set observaciones(value: string) {
    this._observaciones = value;
  }

  /**
   * Setter cargo
   * @param {Cargo} value
   */
  public set cargo(value: Cargo) {
    this._cargo = value;
  }

  /**
   * Setter agente
   * @param {Agente} value
   */
  public set agente(value: Agente) {
    this._agente = value;
  }

  /**
   * Setter situacion_revista
   * @param {SituacionRevista} value
   */
  public set situacion_revista(value: SituacionRevista) {
    this._situacion_revista = value;
  }
}

export interface SituacionRevista {
  id: number;
  descripcion: string;
}
