// Generated by https://quicktype.io

export interface Imenu {
  name:     string;
  icon:     string;
  link:     string;
  children: Child[];
  active  ?: boolean
}

export interface Child {
  name: string;
  link: string;
  active?:boolean
}
