import { Localidad } from '../../ubicacion/localidad/models/localidad';

// Generated by https://quicktype.io

export class Persona {
  private _id: number;
  private _id_nacionalidad: number;
  private _documento: string;
  private _nombre: string;
  private _apellidos: string;
  private _fecha_nacimiento: string;
  private _lugar_nacimiento: string;
  private _sexo: string;
  private _calle: string;
  private _altura: string;
  private _piso: string;
  private _depto: string;
  private _barrio: string;
  private _id_localidad: number;
  private _telefono: string;
  private _localidad: Localidad;

  constructor(
    id: number,
    id_nacionalidad: number,
    documento: string,
    nombre: string,
    apellidos: string,
    fecha_nacimiento: string,
    lugar_nacimiento: string,
    sexo: string,
    calle: string,
    altura: string,
    piso: string,
    depto: string,
    barrio: string,
    id_localidad: number,
    telefono: string,
    localidad: Localidad
  ) {
    this._id = id;
    this._id_nacionalidad = id_nacionalidad;
    this._documento = documento;
    this._nombre = nombre;
    this._apellidos = apellidos;
    this._fecha_nacimiento = fecha_nacimiento;
    this._lugar_nacimiento = lugar_nacimiento;
    this._sexo = sexo;
    this._calle = calle;
    this._altura = altura;
    this._piso = piso;
    this._depto = depto;
    this._barrio = barrio;
    this._id_localidad = id_localidad;
    this._telefono = telefono;
    this._localidad = localidad;
  }

  static getInstance(obj: Object){
    return new Persona(
      obj['id'],
      obj['id_nacionalidad'],
      obj['documento'],
      obj['nombre'],
      obj['apellidos'],
      obj['fecha_nacimiento'],
      obj['lugar_nacimiento'],
      obj['sexo'],
      obj['calle'],
      obj['altura'],
      obj['piso'],
      obj['depto'],
      obj['barrio'],
      obj['id_localidad'],
      obj['telefono'],
      obj['localidad']
    )
  }


  public get ApellidoNombre(): string {
    return `${this.apellidos} ${this.nombre}`;
  }

  public get domicilio(): string {
    if (this.calle === 'S/D' || this.calle === null || this.calle === '') {
      return '';
    }

    let dom = this.calle;
    dom +=
      this.altura === 'S/D' ||
      this.altura.includes('-') ||
      this.altura === null ||
      this.altura === ''
        ? ''
        : ' N° ' + this.altura;
    dom +=
      this.piso === 'S/D' ||
      this.piso.includes('-') ||
      this.piso === null ||
      this.piso === ''
        ? ''
        : ' Piso:  ' + this.piso;
    dom +=
      this.depto === 'S/D' ||
      this.depto.includes('-') ||
      this.depto === null ||
      this.depto === ''
        ? ''
        : ' Depto: ' + this.depto;
    return dom;
  }

  /**
   * Getter id
   * @return {              number}
   */
  public get id(): number {
    return this._id;
  }

  /**
   * Getter id_nacionalidad
   * @return { number}
   */
  public get id_nacionalidad(): number {
    return this._id_nacionalidad;
  }

  /**
   * Getter documento
   * @return {       string}
   */
  public get documento(): string {
    return this._documento;
  }

  /**
   * Getter nombre
   * @return {          string}
   */
  public get nombre(): string {
    return this._nombre;
  }

  /**
   * Getter apellidos
   * @return {       string}
   */
  public get apellidos(): string {
    return this._apellidos;
  }

  /**
   * Getter fecha_nacimiento
   * @return {string}
   */
  public get fecha_nacimiento(): string {
    return this._fecha_nacimiento;
  }

  /**
   * Getter lugar_nacimiento
   * @return {string}
   */
  public get lugar_nacimiento(): string {
    return this._lugar_nacimiento;
  }

  /**
   * Getter sexo
   * @return {            string}
   */
  public get sexo(): string {
    return this._sexo;
  }

  /**
   * Getter calle
   * @return {           string}
   */
  public get calle(): string {
    return this._calle;
  }

  /**
   * Getter altura
   * @return {          string}
   */
  public get altura(): string {
    return this._altura;
  }

  /**
   * Getter piso
   * @return {            string}
   */
  public get piso(): string {
    return this._piso;
  }

  /**
   * Getter depto
   * @return {           string}
   */
  public get depto(): string {
    return this._depto;
  }

  /**
   * Getter barrio
   * @return {          string}
   */
  public get barrio(): string {
    return this._barrio;
  }

  /**
   * Getter id_localidad
   * @return {    number}
   */
  public get id_localidad(): number {
    return this._id_localidad;
  }

  /**
   * Getter telefono
   * @return {        string}
   */
  public get telefono(): string {
    return this._telefono;
  }

  /**
   * Getter localidad
   * @return {       Localidad}
   */
  public get localidad(): Localidad {
    return this._localidad;
  }

  /**
   * Setter id
   * @param {              number} value
   */
  public set id(value: number) {
    this._id = value;
  }

  /**
   * Setter id_nacionalidad
   * @param { number} value
   */
  public set id_nacionalidad(value: number) {
    this._id_nacionalidad = value;
  }

  /**
   * Setter documento
   * @param {       string} value
   */
  public set documento(value: string) {
    this._documento = value;
  }

  /**
   * Setter nombre
   * @param {          string} value
   */
  public set nombre(value: string) {
    this._nombre = value;
  }

  /**
   * Setter apellidos
   * @param {       string} value
   */
  public set apellidos(value: string) {
    this._apellidos = value;
  }

  /**
   * Setter fecha_nacimiento
   * @param {string} value
   */
  public set fecha_nacimiento(value: string) {
    this._fecha_nacimiento = value;
  }

  /**
   * Setter lugar_nacimiento
   * @param {string} value
   */
  public set lugar_nacimiento(value: string) {
    this._lugar_nacimiento = value;
  }

  /**
   * Setter sexo
   * @param {            string} value
   */
  public set sexo(value: string) {
    this._sexo = value;
  }

  /**
   * Setter calle
   * @param {           string} value
   */
  public set calle(value: string) {
    this._calle = value;
  }

  /**
   * Setter altura
   * @param {          string} value
   */
  public set altura(value: string) {
    this._altura = value;
  }

  /**
   * Setter piso
   * @param {            string} value
   */
  public set piso(value: string) {
    this._piso = value;
  }

  /**
   * Setter depto
   * @param {           string} value
   */
  public set depto(value: string) {
    this._depto = value;
  }

  /**
   * Setter barrio
   * @param {          string} value
   */
  public set barrio(value: string) {
    this._barrio = value;
  }

  /**
   * Setter id_localidad
   * @param {    number} value
   */
  public set id_localidad(value: number) {
    this._id_localidad = value;
  }

  /**
   * Setter telefono
   * @param {        string} value
   */
  public set telefono(value: string) {
    this._telefono = value;
  }

  /**
   * Setter localidad
   * @param {       Localidad} value
   */
  public set localidad(value: Localidad) {
    this._localidad = value;
  }
}
